name: Go Build

on:
  push:
    branches:
      - main  # 监听 push 到 main 分支的事件
  pull_request:
    branches:
      - main  # 监听针对 main 分支的 pull request

jobs:
  build:
    runs-on: ubuntu-latest  # 设置运行环境为最新的 Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout 项目的代码

    - name: Set up Go
      uses: actions/setup-go@v3  # 安装 Go 环境
      with:
        go-version: '1.23.5'  # 设置 Go 的版本，根据需要修改

    - name: Cache Go modules
      uses: actions/cache@v3  # 缓存 Go 模块，提升构建速度
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod-

    - name: Install dependencies
      run: go mod tidy  # 安装 Go 模块

    - name: Run tests
      run: go test ./...  # 执行 Go 测试

    - name: Build Go project for Linux amd64
      run: GOOS=linux GOARCH=amd64 go build -v -o main-linux-amd64 .  # 构建 Linux amd64 版

    - name: Build Go project for Linux arm64
      run: GOOS=linux GOARCH=arm64 go build -v -o main-linux-arm64 .  # 构建 Linux arm64 版

    - name: Build Go project for Windows amd64
      run: GOOS=windows GOARCH=amd64 go build -v -o main-windows-amd64.exe .  # 构建 Windows 版


    - name: List files (Debug)
      run: ls -l  # 查看当前目录下的文件

    - name: Upload Linux amd64 binary
      uses: actions/upload-artifact@v4
      with:
        name: linux-amd64-binary
        path: ./main-linux-amd64

    - name: Upload Linux arm64 binary
      uses: actions/upload-artifact@v4
      with:
        name: linux-arm64-binary
        path: ./main-linux-arm64

    - name: Upload Windows amd64 binary
      uses: actions/upload-artifact@v4
      with:
        name: windows-amd64-binary
        path: ./main-windows-amd64.exe